# Required services
# [X] DB
# [X] API
# [] Customer Frontend
# [] Employee Frontend
# [] Admin Frontend

services:
  frontend:
    build: ./frontend
    container_name: grocery_frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: unless-stopped

  api:
    build: ./api
    container_name: grocery_api
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.4
    container_name: grocery_db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db

volumes:
  dbdata: